const axios = require('axios');

module.exports = [
    {
        name: 'ai', 
        alias: ['kira', 'bot', 'ask', 'gpt'],
        category: 'ai',
        description: 'Talk with AI Assistant',
        usage: '.ai <question>',
        async execute(sock, msg, args) {
            const jid = msg.key.remoteJid;
            if (!args[0]) return await sock.sendMessage(jid, { text: '⚠️ Ask something!' }, { quoted: msg });
            
            try {
                const res = await axios.get(`https://eliteprotech-apis.zone.id/talk-ai?prompt=${encodeURIComponent(args.join(' '))}`);
                const replyText = res.data.result || res.data.message || "I couldn't get an answer.";
                await sock.sendMessage(jid, { text: replyText }, { quoted: msg });
            } catch (err) {
                await sock.sendMessage(jid, { text: '❌ *Failed to get AI response.*' }, { quoted: msg });
            }
        }
    },
    {
        name: 'chatgpt',
        category: 'ai',
        description: 'ChatGPT',
        usage: '.chatgpt <query>',
        async execute(sock, msg, args) {
            // 'q' മാറ്റി 'prompt' ആക്കി
            const res = await axios.get(`https://eliteprotech-apis.zone.id/chatgpt?prompt=${encodeURIComponent(args.join(' '))}`);
            await sock.sendMessage(msg.key.remoteJid, { text: res.data.result });
        }
    },
    {
        name: 'copilot',
        category: 'ai',
        description: 'Microsoft Copilot',
        usage: '.copilot <query>',
        async execute(sock, msg, args) {
            // 'q' മാറ്റി 'prompt' ആക്കി
            const res = await axios.get(`https://eliteprotech-apis.zone.id/copilot?prompt=${encodeURIComponent(args.join(' '))}`);
            await sock.sendMessage(msg.key.remoteJid, { text: res.data.result });
        }
    },
   {
        name: 'flux',
        category: 'ai',
        description: 'Generate AI images',
        usage: '.flux <prompt>',
        async execute(sock, msg, args) {
            const jid = msg.key.remoteJid;
            if (!args[0]) return await sock.sendMessage(jid, { text: '⚠️ Please provide a prompt for the image!' }, { quoted: msg });

            await sock.sendMessage(jid, { text: '⏳ Generating...' }, { quoted: msg });
            
            const botName = global.config?.BOT_NAME || process.env.BOT_NAME || 'KIRA X MD';
            const url = `https://eliteprotech-apis.zone.id/flux?prompt=${encodeURIComponent(args.join(' '))}`;
            
            try {
                await sock.sendMessage(jid, { 
                    image: { url: url }, 
                    caption: `✨ Generated by ${botName}` 
                }, { quoted: msg });
            } catch (err) {
                await sock.sendMessage(jid, { text: '❌ *Image generation failed.*' }, { quoted: msg });
            }
        }
    }
];