module.exports = {
    name: "deletingtext",
    alias: ["dtext"],
    category: "logo",
    description: "Generate Deleting Text Logo",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const text = args.join(" ").trim();
        
        // 🔥 Dynamic Bot Name
        const botName = global.config?.BOT_NAME || global.getBotName(botNumber) || 'KIRA X MD';

        if (!text) {
            return sock.sendMessage(
                jid,
                {
                    text:
                        `❌ Example:\n.deletingtext ${botName}`
                },
                { quoted: msg }
            );
        }

        try {
            await sock.sendMessage(jid, {
                react: {
                    text: "🎨",
                    key: msg.key
                }
            });

            const image =
                `https://jerrycoder.oggyapi.workers.dev/ephoto/deletingtext?text=${encodeURIComponent(text)}`;

            await sock.sendMessage(
                jid,
                {
                    image: {
                        url: image
                    },
                    caption:
                        `✨ *Deleting Text Logo*\n📝 Text: ${text}\n\n> *Generated by ${botName}*`
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "✅",
                    key: msg.key
                }
            });

        } catch (e) {
            console.log("DELETINGTEXT ERROR:", e);

            await sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Failed to generate logo."
                },
                { quoted: msg }
            );
        }
    }
};